# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-20 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickevent',
            old_name='url_1',
            new_name='kirr_url',
        ),
        migrations.RenameField(
            model_name='clickevent',
            old_name='update',
            new_name='updated',
        ),
    ]
